### ISSUE TITLE
Broaden the scope

### ISSUE THREAD

**Issue by tpluscode** [HydraCG/extensions#1]
I've been meaning to finally start putting some content here for the Hydra+SHACL extension but while discussing https://github.com/HydraCG/Specifications/issues/234 I thought that maye we could rename this repo to `extensions` and create here more auxiliary specs to extend Hydra

For starters those could be the extensions for SHACL and Profile and both possibly related as mentioned in https://github.com/HydraCG/Specifications/issues/234#issuecomment-839983299

**Comment by alien-mcl** [comment]
What is your reckoning on how many extensions could we expect at the beginning?

**Comment by alien-mcl** [comment]
Aaa, I see now - SHACL would be one extension and Profile (canonical or whatever name it will end up with) another one.

**Comment by alien-mcl** [comment]
I've renamed it to `extensions`. Closing
